### ISSUE TITLE
From for PCGs back into their tuple or array forms

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/randomize#27]
this is mostly dumb but @evrey wanted it

**Comment by Evrey** [comment]
It is indeed dumb, but it adds symmetry. In case one does use the `From` conversion, chances are greater than 0 that the same person might think about using a symmetrical `Into`. I don't see myself even using the `From` variant, though.

**Comment by Lokathor** [comment]
From is mostly there for being the cheapo serde replacement, so it might as well be symetrical
