### ISSUE TITLE
f32_half_open_right needs a new formula

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/randomize#33]
`f32::from_bits(0x3f80_0000 | (the_random_u32 & 0x7fffff)) - 1.0`

same with f64

@thomcc i hope i'm pinging the right person here

**Comment by thomcc** [comment]
`f32_half_open_right` is what i was describing. your link for the closed impl was pretty convincing why my clever trick would fail

**Comment by Lokathor** [comment]
For reference, the f64 version was

```rust
/// `u64` to `[0.0, 1.0)`
#[inline]
pub fn f64_half_open_right(u: u64) -> f64 {
  f64::from_bits(0x3ff0000000000000 | (u & 0xFFFFFFFFFFFFF)) - 1.0
}
```

from thomcc:
> 0x3f80_0000 is 1.0f32.to_bits, it would be 1.0f64.to_bits 0x3ff0000000000000. the mask is the mantissa space, e.g. all those zeros
