### ISSUE TITLE
Better float distribution

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/randomize#34]
* Our current float distribution stuff is quick and dirty, giving `u32 -> f32`, and there's a large number of possible `[0, 1)` values that **cannot** be generated by our quick and dirty technique. It's as uniform as possible given the type signature, but it ends up being granular if you want to be really precise about your `f32` outputs.
* @orlp proposes that we add a distribution that can generate more possible numbers in the `[0, 1)` range, while maintaining that for `p` in `[0, 1)`, we would have `output<p` as close as possible to `p%` of the time. The catch is that it uses a non-fixed number of generator outputs so we have to actually pass the generator not just a single `u32`.
  * This would be a _new_ method and we wouldn't remove the old method, but we'd document that it's quick and dirty and people can pick how they want to go on that.

The code would be roughly as follows (they wrote the example using `rand`):

```rust
use rand::{Rng, SeedableRng};
use rand_pcg::Pcg32;

// Returns k with probability 2^(k-1).
fn binary_exp_distr<R: Rng>(rng: &mut R) -> u32 {
    let r: u32 = rng.gen();
    if r > 0 {
        r.trailing_zeros()
    } else {
        32 + binary_exp_distr(rng)
    }
}

// Returns a random float in [0, 1).
fn gen_float<R: Rng>(rng: &mut R) -> f32 {
    let r: u32 = rng.gen();
    let mantissa = r >> (32 - 23);
    let rand_bit: bool = (r & 1) != 0;
    let restbits: u8 = (r >> 1) as u8;

    // If our mantissa is zero half of the time we must increase our exponent.
    let increment_exponent = (mantissa == 0 && rand_bit) as i32;

    // We can use restbits to save more calls to the rng 255 out of 256 times.
    let mut exponent: i32 =
        -1 + increment_exponent -
        if restbits > 0 {
            restbits.trailing_zeros() as i32
        } else {
            8 + binary_exp_distr(rng) as i32
        };

    // It is very unlikely our exponent is valid at this point, but keep
    // regenerating it until it is.
    while exponent < -127 || exponent > -1 {
        // Note: for an inclusive range of [0, 1], allow exponent == 0. We can
        // only get exponent == 0 if increment_exponent is true, which means the
        // mantissa must be zero.
        exponent = -1 + increment_exponent - binary_exp_distr(rng) as i32;
    }

    f32::from_bits((((exponent + 127) as u32) << 23) | mantissa)
}

fn main() {
    let mut rng = Pcg32::seed_from_u64(4);
    loop {
        println!("{:?}", gen_float(&mut rng));
    }
}
```
Based on this paper: http://allendowney.com/research/rand/downey07randfloat.pdf

(NOTE: the rust port is currently untested)

**Comment by orlp** [comment]
Just leaving a comment here so I'm actually pingable if something is unclear.

**Comment by icefoxen** [comment]
I found yet another method described here: https://mumble.net/~campbell/2014/04/28/uniform-random-float and implemented here: https://mumble.net/~campbell/2014/04/28/random_real.c .  Looks like it might end up being similar, or at least has similar concerns.

**Comment by Lokathor** [comment]
@orlp so the comment at the top says `[0, 1)`, and the comment inside the function says `[0, 1]`, which is it?

**Comment by orlp** [comment]
@Lokathor The comment says that if you wish to have a range of `[0, 1]` (as opposed to `[0, 1)` which the function implements), you must allow `exponent == 0`. But since the `while loop` loops if `exponent > -1`, it does **not** allow `exponent == 0` and thus we don't have `1` in the output domain.

**Comment by orlp** [comment]
I do believe there's a typo in this comment:

    // It is very unlikely our exponent is valid at this point, but keep
    // regenerating it until it is.

and that it should say `very unlikely our exponent is invalid`.

**Comment by orlp** [comment]
To actually implement the idea the comment was meant to convey, you can make the function more flexible by adding a parameter `include_one: bool`, and then changing the line

    while exponent < -127 || exponent > -1 {

to

    let max_exp = if allow_one { 0 } else { -1 };
    while exponent < -127 || exponent > max_exp  {

**Comment by Lokathor** [comment]
Okay, i follow now.

**Comment by Lokathor** [comment]
@orlp is there a similar easy adjustment that lets you pick between 0 being included or excluded?

**Comment by orlp** [comment]
Actually, thinking more about my trick, I realize it is ever so slightly biased. The original method from the paper makes sense and is correct:


```rust
// Returns a random float in [0, 1].
fn gen_float_inclusive<R: Rng>(rng: &mut R) -> f32 {
    let r: u32 = rng.gen();
    let mantissa = r >> (32 - 23);
    let rand_bit: bool = (r & 1) != 0;
    let restbits: u8 = (r >> 1) as u8;

    // If our mantissa is zero half of the time we must increase our exponent.
    let increment_exponent = (mantissa == 0 && rand_bit) as i32;

    // We can use restbits to save more calls to the rng 255 out of 256 times.
    let mut exponent: i32 =
        -1 + increment_exponent -
        if restbits > 0 {
            restbits.trailing_zeros() as i32
        } else {
            8 + binary_exp_distr(rng) as i32
        };

    // It is very unlikely our exponent is invalid at this point, but keep
    // regenerating it until it is valid.
    while exponent < -127 || exponent > 0 {
        exponent = -1 + increment_exponent - binary_exp_distr(rng) as i32;
    }

    f32::from_bits((((exponent + 127) as u32) << 23) | mantissa)
}
```

Why is my modification to a half-open range biased? Because it would distribute the chance of rolling `1` not to all other numbers uniformly, but only to other numbers with mantissa zero. This bias is miniscule, but nevertheless exists. Therefore I think the only correct way is to simply restart if you hit `0` or `1`:

```rust
fn gen_float<R: Rng>(rng: &mut R, include_zero: bool, include_one: bool) -> f32 {
    loop {
        let r = gen_float_inclusive(rng);
        if ((r != 0.0) | include_zero) & ((r != 1.0) | include_one) {
            return r;
        }
    }
}
```

**Comment by Lokathor** [comment]
Okay, also, this code here:
```rust
// Returns k with probability 2^(k-1).
fn binary_exp_distr<R: Rng>(rng: &mut R) -> u32 {
```
That comment has to be somehow wrong, i think?

if `k` = 1, the probability would be 2^(1-1)==2^0==1, and it clearly doesn't return `1` all of the time.

**Comment by orlp** [comment]
> 
> 
> Okay, also, this code here:
> 
> ```rust
> // Returns k with probability 2^(k-1).
> fn binary_exp_distr<R: Rng>(rng: &mut R) -> u32 {
> ```
> 
> That comment has to be somehow wrong, i think?
> 
> if `k` = 1, the probability would be 2^(1-1)==2^0==1, and it clearly doesn't return `1` all of the time.

Eh, well, for `k = 2` it goes even more wrong :)

It's a typo, it should be `Returns k with probability 2^(-k-1).`,

**Comment by Lokathor** [comment]
I'm close to an alpha of 4.0

however, in 3.0 there was a method for `[-1.0, 1.0]`, which seems potentially useful. Would that be possible to do evenly

The "fallback" would be to, i guess, generate `[0.0, 1.0]`, then adjust the value to fit in `[-1.0, 1.0]` via `x * 2.0 - 1.0`

**Comment by orlp** [comment]
@Lokathor `x * 2.0 - 1.0` would be unnecessarily biased if you can do the operation perfectly at high performance. And we can, just using 1 bit of randomness. Set the top bit (the sign bit) to a random bit and done!

It's best if you rewrite the above function to take this bit from `restbits` to minimize calls to the RNG. E.g.

```
// Returns a random float in [-1, 1].
fn rand_signed_f32_inclusive<R: Rng>(rng: &mut R) -> f32 {
    let r: u32 = rng.gen();
    let mantissa = r >> (32 - 23);
    let rand_bit: bool = (r & 1) != 0;
    let sign_bit: bool = (r & 2) != 0;
    let restbits: u8 = (r >> 2) as u8;

    // If our mantissa is zero half of the time we must increase our exponent.
    let increment_exponent = (mantissa == 0 && rand_bit) as i32;

    // We can use restbits to save more calls to the rng 255 out of 256 times.
    let mut exponent: i32 =
        -1 + increment_exponent -
        if restbits > 0 {
            restbits.trailing_zeros() as i32
        } else {
            8 + binary_exp_distr(rng) as i32
        };

    // It is very unlikely our exponent is invalid at this point, but keep
    // regenerating it until it is valid.
    while exponent < -127 || exponent > 0 {
        exponent = -1 + increment_exponent - binary_exp_distr(rng) as i32;
    }

    f32::from_bits((((exponent + 127) as u32) << 23) | ((sign_bit as u32) << 31) | mantissa)
}
```

Of course you can take the common parts out in a separate function.

**Comment by orlp** [comment]
@Lokathor `x * 2.0 - 1.0` would be unnecessarily biased if you can do the operation perfectly at high performance. And we can, just using 1 bit of randomness. Set the top bit (the sign bit) to a random bit and done!

It's best if you rewrite the above function to take this bit from `restbits` to minimize calls to the RNG. E.g.

```
// Returns a random float in [-1, 1].
fn rand_signed_f32_inclusive<R: Rng>(rng: &mut R) -> f32 {
    let r: u32 = rng.gen();
    let mantissa = r >> (32 - 23);
    let rand_bit: bool = (r & 1) != 0;
    let sign_bit: bool = (r & 2) != 0;
    let restbits = (r >> 2) & ((1 << 7) - 1); // 7 bits of unused RNG left.

    // If our mantissa is zero half of the time we must increase our exponent.
    let increment_exponent = (mantissa == 0 && rand_bit) as i32;

    // We can use restbits to save more calls to the rng 255 out of 256 times.
    let mut exponent: i32 =
        -1 + increment_exponent -
        if restbits > 0 {
            restbits.trailing_zeros() as i32
        } else {
            8 + binary_exp_distr(rng) as i32
        };

    // It is very unlikely our exponent is invalid at this point, but keep
    // regenerating it until it is valid.
    while exponent < -127 || exponent > 0 {
        exponent = -1 + increment_exponent - binary_exp_distr(rng) as i32;
    }

    f32::from_bits((((exponent + 127) as u32) << 23) | ((sign_bit as u32) << 31) | mantissa)
}
```

Of course you can take the common parts out in a separate function.

**Comment by Lokathor** [comment]
cool.

And I assume that the f64 version is the same as all this, we'd just bump up some constants to use the f64 mantissa and exponent factor and all that?

**Comment by orlp** [comment]
> cool.
> 
> And I assume that the f64 version is the same as all this, we'd just bump up some constants to use the f64 mantissa and exponent factor and all that?

It's a bit tricky and you have to be careful, I just had to fix two bugs in the above code, but in theory yes. Let me write a version that has less magic numbers in it.

**Comment by Lokathor** [comment]
Okay, I've got both `next_f32_norm` and `next_f32_signed_norm` pushed up to the repository.

Names could be bikeshed if there's better names, but none jump out at me.

**Comment by orlp** [comment]
This is like a "mother" version you could derive the others from, with all magic numbers explained.

```rust
fn ieee754_random<R: Rng>(rng: &mut R) -> f32 {
    // Returns random number in [0, 1] or [-1, 1] depending on signed.
    let signed = true;
    let bit_width = 32;
    let exponent_bias = 127;
    let num_mantissa_bits = 23;
    let num_rest_bits = bit_width - num_mantissa_bits - 1 - signed as i32;
    let r: u32 = rng.gen();

    assert!(num_rest_bits >= 0);
    assert!(std::mem::size_of(r)*8 == bit_width);

    let mantissa = r >> (bit_width - num_mantissa_bits);
    let sign_mask = r << (bit_width - 1);
    let rand_bit, rest_bits;
    if signed {
        rand_bit = (r & 2) != 0;
        rest_bits = (r >> 2) & ((1 << num_rest_bits) - 1);
    } else {
        rand_bit = (r & 1) != 0;
        rest_bits = (r >> 1) & ((1 << num_rest_bits) - 1);
    }

    // If our mantissa is zero half of the time we must increase our exponent.
    let increment_exponent = (mantissa == 0 && rand_bit) as i32;

    // We can use rest_bits to save more calls to the rng.
    let mut exponent: i32 =
        -1 + increment_exponent -
        if rest_bits > 0 {
            rest_bits.trailing_zeros() as i32
        } else {
            num_rest_bits + binary_exp_distr(rng) as i32
        };

    // It is very unlikely our exponent is invalid at this point, but keep
    // regenerating it until it is valid.
    while exponent < -exponent_bias || exponent > 0 {
        exponent = -1 + increment_exponent - binary_exp_distr(rng) as i32;
    }

    f32::from_bits(sign_mask | (((exponent + exponent_bias) as u32) << num_mantissa_bits) | mantissa)
}
```

**Comment by Lokathor** [comment]
Okay, it's pushed, you can give it a look.

**Comment by orlp** [comment]
Some feedback (which I'll just do here):

1. I strongly suggest something else than `next_f32_norm`. `norm` would refer to a normally distributed random variable, which is not what you wish to imply. I would maybe suggest something along the lines of unit uniform, or just `rand` which is what this is usually called in other languages.

2. I'm not sure if you want `next_binary_exp_distr` to actually be public. Up to you.

3. I have no idea what `Performs a "step roll" according to the 4e chart.` means.

4. The random number generation code looks good.

5. You might want to include versions for `[0, 1)` and `(-1, 1)`.

**Comment by Lokathor** [comment]
> I have no idea what Performs a "step roll" according to the 4e chart. means.

that one is from a particular paper and pencil rpg, not intended to necessarily make sense to everyone. I could note that better on the method I suppose.

**Comment by Lokathor** [comment]
1) renamed to "unit" and "signed unit"
2) made binary_exp private, as well as the ieee754 functions private.
3) Improved the docs for the RPG related functions (and added some more!)
4) yay!
5) i might add more later, i'm not sure how much i'll need f32 to begin with (but i knew i at least wanted the basics to be solid).

**Comment by Lokathor** [comment]
Closing this up, since we seem to have floats sorted.
