### ISSUE TITLE
randomize('Aa0!',10) doesnt provide a number.

### ISSUE THREAD

**Issue by saleemadat** [Lokathor/randomize#35]
I'm using randomatic 3.1.1, and when I test this code below, the string generated returned does not produce a number in the string where it should do. 

``
export function generatePassword() {
 while(true) {
    const result =  randomize('Aa0!', 9);
    console.log(result)
    if (!/d/.test((result))) {
      throw new Error('NO NUMBER !')
    }
  }
}

**Comment by Lokathor** [comment]
This uh, is a rust library.

And whatever you wrote there isn't rust code.

I think you have the wrong repo.
