### ISSUE TITLE
Restore git history for previous versions

### ISSUE THREAD

**Issue by StrikeForceZero** [Lokathor/randomize#4]
I noticed the sources for previous versions of this crate are not tracked in this repo, and was wondering if they can be restored.

**Comment by Wolvereness** [comment]
For example, pushing 35f1951d25c8dfab3e7df825bc72f25c69118f8a if it could be recovered to a separate branch (for historical reasons).

**Comment by Lokathor** [comment]
At one point I deleted many old and untouched repos of stuff that i figured was basically only used by me anyway, then half a year later i decided to make another totally new version of `randomize` and so I just made a fresh git repo under the same name and just threw it out under a new major version.

The ancient versions only exist in the crates.io archives at this point.

**Comment by StrikeForceZero** [comment]
Ah, ok. Thanks for clarifying.
